### ISSUE TITLE
Make the CIString constructor private

### ISSUE THREAD

**Issue by chuwy** [axiomed/CaseInsensitive.lean#3]
Currently, we can create the `CIString` using the default constructor:

```lean
def foo: CIString := { hashValue := 42, value := "foo" }
def bar := CIString.mk 42 "bar"
```

At least for latter the following should work out:

```lean
structure CIString where
  private mk ::
  private hashValue : Int
  value : String
```

Less certain about the former.

**Comment by samueldurantes** [comment]
It's possible not to allow the first occurrence just the privating `mk` function, but I don't know if is possible not to allow this occurrence:

```lean
def foo: CIString := { hashValue := 42, value := "foo" }
```

However I will fix the first occurrence, but I leaving open this issue because second occurrence...
